draw_config:
  # key dimensions, non-ortho layouts use key_h for width as well
  # key_w: 100 # This doesn't seem to do anything? 🤔
  key_h: 58

  # keys border radius
  key_rx: 4
  key_ry: 4

  # key labels line spacing for multi-line labels
  line_spacing: 1

  # combo box dimensions
  combo_w: 25
  combo_h: 38

  # padding from the edge of cap to top and bottom legends
  small_pad: 4

  # Padding between keys
  inner_pad_w: 1.85
  inner_pad_h: 1.85

  # padding between layers
  outer_pad_w: 27
  outer_pad_h: 35

  # gap between two halves for ortho layout generator
  # split_gap: 20 # This doesn't seem to have any effect either? 🤔

  # as it reads on the tin can, this comment is here for consistency
  append_colon_to_layer_header: false

  # shrink font size for legends wider than this many chars, set to 0 to disable
  # ideal value depends on the font size defined in svg_style and width of the boxes
  shrink_wide_legends: 5

  # Glyphs dimensions
  glyph_tap_size: 18
  glyph_hold_size: 18
  glyph_shifted_size: 1

  # Custom CSS
  svg_style: |
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        /*
         * ====================
         * Theme Variables
         * ====================
         */

        --logo-path: none;
        --logo-size: 12%;
        --logo-position: 49.5% 5%;

        /* === Colors === */

        --color--material--blue--50: rgb(227, 242, 253);
        --color--material--blue--100: rgb(187, 222, 251);
        --color--material--blue--200: rgb(144, 202, 249);
        --color--material--blue--300: rgb(100, 181, 246);
        --color--material--blue--400: rgb(66, 165, 245);
        --color--material--blue--500: rgb(33, 150, 243);
        --color--material--blue--600: rgb(30, 136, 229);
        --color--material--blue--700: rgb(25, 118, 210);
        --color--material--blue--800: rgb(21, 101, 192);
        --color--material--blue--900: rgb(13, 71, 161);
        --color--material--blue--a100: rgb(130, 177, 255);
        --color--material--blue--a200: rgb(68, 138, 255);
        --color--material--blue--a400: rgb(41, 121, 255);
        --color--material--blue--a700: rgb(41, 98, 255);

        --color--material--blue-gray--50: rgb(236, 239, 241);
        --color--material--blue-gray--100: rgb(207, 216, 220);
        --color--material--blue-gray--200: rgb(176, 190, 197);
        --color--material--blue-gray--300: rgb(144, 164, 174);
        --color--material--blue-gray--400: rgb(120, 144, 156);
        --color--material--blue-gray--500: rgb(96, 125, 139);
        --color--material--blue-gray--600: rgb(84, 110, 122);
        --color--material--blue-gray--700: rgb(69, 90, 100);
        --color--material--blue-gray--800: rgb(55, 71, 79);
        --color--material--blue-gray--900: rgb(38, 50, 56);

        --color--material--purple--50: rgb(243, 229, 245);
        --color--material--purple--100: rgb(225, 190, 231);
        --color--material--purple--200: rgb(206, 147, 216);
        --color--material--purple--300: rgb(186, 104, 200);
        --color--material--purple--400: rgb(171, 71, 188);
        --color--material--purple--500: rgb(156, 39, 176);
        --color--material--purple--600: rgb(142, 36, 170);
        --color--material--purple--700: rgb(123, 31, 162);
        --color--material--purple--800: rgb(106, 27, 154);
        --color--material--purple--900: rgb(74, 20, 140);
        --color--material--purple--a100: rgb(234, 128, 252);
        --color--material--purple--a200: rgb(224, 64, 251);
        --color--material--purple--a400: rgb(213, 0, 249);
        --color--material--purple--a700: rgb(170, 0, 255);

        --color--turquoise--500: rgb(51, 204, 204);

        --color--bg: transparent;
        --color--text: var(--color--material--blue-gray--900);

        --color--layer--text: var(--color--material--blue-gray--400);

        --color--key--bg: var(--color--material--blue-gray--50);
        --color--key--border: white;
        --color--key--text--tap: var(--color--text);
        #--color--key--text--shifted: var(--color--material--blue-gray--500);
        --color--key--text--shifted: transparent;
        --color--key--text--hold: var(--color--material--blue-gray--500);

        --color--combo--bg: var(--color--material--blue-gray--100);
        --color--combo--border: var(--color--combo--bg);
        --color--combo--dendron: var(--color--combo--border);
        --color--combo--text--tap: var(--color--material--blue-gray--800);
        --color--combo--text--shifted: var(--color--material--blue-gray--400);
        --color--combo--text--hold: var(--color--combo--text--tap);

        --color--trans--bg: transparent;
        --color--trans--border: var(--color--trans--bg);
        --color--trans--text--tap: var(--color--trans--border);
        --color--trans--text--shifted: var(--color--trans--text--tap);
        --color--trans--text--hold: var(--color--trans--text--tap);

        --color--none--bg: var(--color--trans--bg);
        --color--none--border: var(--color--trans--border);
        --color--none--text--tap: var(--color--trans--text--tap);
        --color--none--text--shifted: var(--color--trans--text--shifted);
        --color--none--text--hold: var(--color--trans--text--hold);

        --color--ghost--bg: var(--color--trans--bg);
        --color--ghost--border: var(--color--trans--border);
        --color--ghost--text--tap: var(--color--trans--text--tap);
        --color--ghost--text--shifted: var(--color--trans--text--shifted);
        --color--ghost--text--hold: var(--color--trans--text--shifted);

        /*
         * ====================
         * /End Theme Variables
         * ====================
         */

        font-family: REM,SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 18px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: var(--color--text);
        background-color: var(--color--bg);
        background-image: var(--logo-path);
        background-repeat: no-repeat;
        background-position: var(--logo-position);
        background-size: var(--logo-size) auto;
    }

    rect,
    path {
      shape-rendering: geometricPrecision;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        line-height: 1;
    }

    /* Layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        paint-order: stroke;
        fill: var(--color--layer--text);
        dominant-baseline: text-before-edge;
    }


    /* Keys */
    rect.key,
    rect.combo {
        fill: var(--color--key--bg);
        stroke: var(--color--key--border);
    }
    .tap {
        fill: var(--color--key--text--tap);
    }
    .shifted,
    .hold {
        font-size: 18px;
        text-anchor: middle;
    }
    .shifted {
        dominant-baseline: hanging;
        fill: var(--color--key--text--shifted);
        translate: -25px 2px;
    }
    .hold {
        dominant-baseline: ideographic;
        fill: var(--color--key--text--hold);
    }

    /*
     * Combos
     */
    .combo {
        --color--key--bg: var(--color--material--purple--100);
        --color--key--border: var(--color--combo--border);
        --color--key--text--tap: var(--color--combo--text--tap);
        --color--key--text--shifted: var(--color--combo--text--shifted);
        --color--key--text--hold: var(--color--combo--text--hold);
    }
    rect.combo {
        stroke-width: 0;
    }
    path.combo {
        stroke-width: 1;
        stroke: var(--color--combo--dendron);
        stroke-dasharray: 2, 2;
        fill: none;
    }
    .combo.tap {
        font-size: 12px;
    }
    .combo.shifted {
        font-size: 13px;
        translate: -9px -2px;
    }
    .combo.hold {
        font-size: 15px;
        /* translate: 2px 0px; */
    }

    /*
     * Transparent, None, and Ghost Keys
     */
    .trans{
      opacity: 0.9;
    },
    .none {
      opacity: 0.1;
    },
    .ghost {
      opacity: 0.4;
    }
    .trans {
        --color--key--bg: var(--color--material--purple--200);
        --color--key--border: var(--color--material--purple--100);
        --color--key--text--tap: var(--color--material--purple--50);
        --color--key--text--shifted: var(--color--trans--text--shifted);
        --color--key--text--hold: var(--color--trans--text--hold);
    }
    .none {
        --color--key--bg: var(--color--none--bg);
        --color--key--border: transparent;
        --color--key--text--tap: transparent;
        --color--key--text--shifted: transparent;
        --color--key--text--hold: transparent;
    }
    .ghost {
        --color--key--bg: var(--color--ghost--bg);
        --color--key--border: var(--color--ghost--border);
        --color--key--text--tap: var(--color--ghost--text--tap);
        --color--key--text--shifted: var(--color--ghost--text--shifted);
        --color--key--text--hold: var(--color--ghost--text--hold);
    }

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Layers
    "&smart_num L2 0":
      shifted: $$mdi:alpha-w-box$$
      tap: L2
      hold: $$mdi:gesture-tap-hold$$
    "&csl Fn":
      tap: Fn
      hold: $$mdi:close-box$$
    "&csl L2":
      tap: L2
      hold: $$mdi:close-box$$
    "&cmo Fn":
      tap: $$mdi:close-box$$
      hold: Fn
    "&cmo L2":
      tap: $$mdi:close-box$$
      hold: L2

    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$     

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$

    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    LGUI: $$mdi:apple-keyboard-command$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$    
    PG_UP: $$mdi:page-first$$
    PG_DN: $$mdi:page-last$$
    HOME: $$mdi:chevron-triple-left$$
    END: $$mdi:chevron-triple-right$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    SPACE: $$mdi:keyboard-space$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DEL: $$mdi:backspace-reverse-outline$$

  zmk_combos:
    cb_gui:
      align: bottom
     # o: 2.12  
      arc_scale: 2.03
    cb_alt:
      align: bottom
      arc_scale: 2.03
    cb_q:
      align: left
      offset: -.5
